version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: dkogwksc44kgc0gg4ksccws0
      DB_PORT: 3306
      DB_DATABASE: default
      DB_USERNAME: mysql
      DB_PASSWORD: njaHEkOr8LYaKpmwsUc1ZRrLKjEsrUsxeg9WxSHlqFHQ32y5weElpJgiiiVBnNi0
