services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    volumes:
      - '/data/coolify/applications/pwg088c4g0c4soo48c8o0k88/src:/var/www/html'
    environment:
      DB_CONNECTION: mysql
      DB_HOST: dkogwksc44kgc0gg4ksccws0
      DB_PORT: 3306
      DB_DATABASE: default
      DB_USERNAME: mysql
      DB_PASSWORD: njaHEkOr8LYaKpmwsUc1ZRrLKjEsrUsxeg9WxSHlqFHQ32y5weElpJgiiiVBnNi0
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: pwg088c4g0c4soo48c8o0k88
      COOLIFY_CONTAINER_NAME: web-pwg088c4g0c4soo48c8o0k88-020713118140
      COOLIFY_URL: 'https://xprohotel.hostspot.online'
      COOLIFY_FQDN: xprohotel.hostspot.online
    container_name: web-pwg088c4g0c4soo48c8o0k88-020713118140
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.419
      - coolify.applicationId=5
      - coolify.type=application
      - coolify.name=web-pwg088c4g0c4soo48c8o0k88-020713118140
      - coolify.resourceName=muhammad-ridwan01xprohoteldockermain-fgc80s0cs0skkkgcgos0wg40
      - coolify.projectName=my-first-project
      - coolify.serviceName=muhammad-ridwan01xprohoteldockermain-fgc80s0cs0skkkgcgos0wg40
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.routers.web.entryPoints=https
      - traefik.http.routers.web.rule=Host(`xprohotel.hostspot.online`)
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=letsencrypt
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.routers.web.middlewares=gzip

    networks:
      pwg088c4g0c4soo48c8o0k88: null

volumes: { }
networks:
  pwg088c4g0c4soo48c8o0k88:
    name: pwg088c4g0c4soo48c8o0k88
    external: true
configs: { }
secrets: { }
