services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    container_name: php-xprohotel
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - "traefik.http.routers.xpro.rule=Host(`xprohotel.hostspot.online`)"
      - traefik.http.routers.xpro.entryPoints=http
      - traefik.http.middlewares.xpro-gzip.compress=true
      - traefik.http.routers.xpro.middlewares=xpro-gzip
    networks:
      - coolify

networks:
  coolify:
    external: true
