services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    container_name: php-xprohotel
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - "traefik.http.routers.xpro.rule=Host(`xprohotel.hostspot.online`)"
      - traefik.http.routers.xpro.entryPoints=http
      - traefik.http.middlewares.xpro-gzip.compress=true
      - traefik.http.routers.xpro.middlewares=xpro-gzip
    networks:
      - coolify
    environment:
      DB_CONNECTION: mysql
      DB_HOST: dkogwksc44kgc0gg4ksccws0
      DB_PORT: 3306
      DB_DATABASE: default
      DB_USERNAME: mysql
      DB_PASSWORD: njaHEkOr8LYaKpmwsUc1ZRrLKjEsrUsxeg9WxSHlqFHQ32y5weElpJgiiiVBnNi0

networks:
  coolify:
    external: true