version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-native
    volumes:
      - ./src:/var/www/html
    user: "33:33"
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.type=application
      - traefik.enable=true
      - traefik.http.routers.native.rule=Host(`xprohotel.hostspot.online`)
      - traefik.http.routers.native.entryPoints=http
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.routers.native.middlewares=gzip
    networks:
      - coolify

networks:
  coolify:
    external: true
