version: "3.9"
services:
  app:
    image: php:8.2-apache
    container_name: php-app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      - coolify
networks:
  coolify:
    external: true
